name: CI & Deploy to EC2

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

env:
  EC2_PATH: ${{ secrets.EC2_PATH }}
  PYTHON_VERSION: '3.11'

jobs:
  build:
    name: 🧪 Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          export PYTHONPATH="${GITHUB_WORKSPACE}:${PYTHONPATH}"
          pytest --maxfail=1 --disable-warnings -q

  deploy:
    name: 🚀 Deploy to EC2
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_PATH }}
            git pull --ff-only
            source venv/bin/activate
            pip install -r requirements.txt --quiet
            # Ensure instance directory exists for database
            mkdir -p instance
            # Initialize database (tables created automatically on app startup)
            export PYTHONPATH="$(pwd):${PYTHONPATH}"
            python -c "from app import create_app; app = create_app(); print('Database initialized')" || true
            sudo systemctl restart myapp
            sleep 2
            # Health check
            curl -f http://localhost:8000/health || echo "Health check failed"