name: SSH Connectivity Test

on: [workflow_dispatch]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client
      - name: Test SSH to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY:  ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${EC2_KEY}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'echo "SSH OK from GitHub Actions"'